services:
    lcn.include_assets:
        class: Lcn\IncludeAssetsBundle\Service\IncludeAssets
        arguments: [@lcn.template_block]

    lcn.twig.include_assets_extension:
        class: Lcn\IncludeAssetsBundle\Twig\IncludeAssetsExtension
        arguments: [@lcn.include_assets]
        tags:
            - { name: twig.extension }
