services:
    lcn.include_assets:
        class: Lcn\IncludeAssetsBundle\Service\IncludeAssets
        arguments: ['/bundles/lcnincludeassets/dist/lcn_load_stylesheet.min.js']

    lcn.twig.include_assets_extension:
        class: Lcn\IncludeAssetsBundle\Twig\IncludeAssetsExtension
        arguments: ["@lcn.include_assets"]
        tags:
            - { name: twig.extension }

    lcn.include_assets_response_injector_listener:
        class: Lcn\IncludeAssetsBundle\EventListener\IncludeAssetsResponseInjectorListener
        arguments: ["@lcn.include_assets"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

